name: Generate

on:
    schedule:
        - cron: "30 21 * * SUN"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: fregante/setup-git-user@v1
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Generate
              run: |
                  yarn add moment lodash.shuffle && yarn generate
                  git add function/files && git commit -m "auto-gen timetable: $(date)" && git push
